### ISSUE TITLE
missing documentation on var.azure_region

### ISSUE THREAD

**Issue by jessebax** [claranet/terraform-azurerm-service-bus#1]
In the README it has code which references var.azure_region. However, this is not listed in the inputs documentation.

**Comment by rossifumax** [comment]
Hello @jessebax ! 

In the example of the README, you're right that we use `var.azure_region`, but it's in the azure-region module (`claranet/regions/azurerm`). You can find the module here : https://github.com/claranet/terraform-azurerm-regions with the documentation on the `var.azure_region` variable. :slightly_smiling_face: 

If it's ok for you, i let you close the issue :wink: 

Have a good day !
