### ISSUE TITLE
Multiple Topic and Subscription creation

### ISSUE THREAD

**Issue by Nitesh1730** [claranet/terraform-azurerm-service-bus#3]
Can you please add template to create Multiple Topic and Subscription? After topic_id and subscription id added subscription_id required unable to set the logic to create topics and associated subscription by just passing name as a variables.

terraform {
   required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.13.0"
    }

**Comment by raswinraaj** [comment]
Any idea if this feature will be added?

**Comment by Shr3ps** [comment]
Hello, we implemented this in our private beta. Should be available on the next major release after testing.

**Comment by Shr3ps** [comment]
Implemented in `v7.0.0` release.
