### ISSUE TITLE
Allow "zone redundant" set to true in namespace

### ISSUE THREAD

**Issue by sourabhsharma487** [claranet/terraform-azurerm-service-bus#4]
While provisioning the service bus namespace, by default value of zone_redundant is false. 

By using this module, there is no way to enable it. Would it be possible if you may please add the below parameter in the below file:

File: https://github.com/claranet/terraform-azurerm-service-bus/blob/master/r-servicebus-namespaces.tf
Parameter: 
`
r-servicebus-namespaces.tf:

resource "azurerm_servicebus_namespace" "servicebus_namespace" {
  for_each            = var.servicebus_namespaces_queues
  name                = lookup(each.value, "custom_name", azurecaf_name.servicebus_namespace[each.key].result)
  location            = var.location
  resource_group_name = var.resource_group_name

  sku      = lookup(each.value, "sku", "Basic")
  capacity = lookup(each.value, "capacity", lookup(each.value, "sku", "Basic") == "Premium" ? 1 : 0)
zone_redundant = var.zone_redundant   #true/false

  tags = merge(
    local.default_tags,
    var.extra_tags,
  )
}
`

`
variables.tf: 

variable "zone_redundant" {
   type = bool
}
`

**Comment by Shr3ps** [comment]
Hello,

thanks for your issue, this has been added to our backlog. It should be released soon after internal review.

**Comment by Shr3ps** [comment]
Hello, this has been added to latest release. Thanks.
